base_url = "https://ethereal.carboxi.de"

# about me
author ="(prasanganiraula2016@gmail.com) Prasanga Niraula"
title = "Ethereal's logs"
description = "I just write things."

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = false}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

# extra stuff
[extra]
email = "prasanganiraula2016@gmail.com"
profile = "/thumbnail.png"
note = "I just love to write, that's all."
