base_url = "https://log.preranasubedi.com.np"

# about me
author ="(me@preranasubedi.com.np) Prerana Subedi"
title = "sunakhari's logs"
description = "I just write things."

# disable sass and search index
compile_sass = false
build_search_index = false

# generate atom feed
feed_filenames = [ "atom.xml", "rss.xml" ]
generate_feeds = true

# enable tags
taxonomies = [
    {name = "tags", output = false}
]

# enable code highlighting
[markdown]
highlight_code = true
highlight_theme = "base16-ocean-light"

# extra stuff
[extra]
email = "me@preranasubedi.com.np"
profile = "/thumbnail.png"
note = "I love to write, that's all."
